// Media execution is recorded through the existing BRAINK cloud dispatcher.
const chunkSize=8*1024*1024,maxBytes=2*1024*1024*1024;
const json=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'private,no-store'}});
const stamp=()=>new Date().toISOString();
const hash=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');
const validId=id=>typeof id==='string'&&/^[a-f0-9-]{36}$/.test(id);
const row=async(db,table,id)=>{const r=await db.prepare(`SELECT document FROM ${table} WHERE id=?`).bind(id).first();return r?JSON.parse(r.document):null;};
async function input(request){const text=await request.text();if(text.length>65536)throw Error('Request exceeds 64 KiB');return JSON.parse(text);}
export function validateEdit(v){if(!v||!Number.isFinite(v.start)||!Number.isFinite(v.end)||v.start<0||v.end<=v.start||!Number.isFinite(v.gain)||v.gain<0||v.gain>2)throw Error('Choose a valid start, end and volume.');if(typeof v.title!=='string'||!v.title.trim()||v.title.length>100)throw Error('Title must contain 1–100 characters.');if(typeof v.description!=='string'||v.description.length>5000)throw Error('Description exceeds 5,000 characters.');return {start:v.start,end:v.end,gain:v.gain,title:v.title.trim(),description:v.description,transcript:typeof v.transcript==='string'?v.transcript.slice(0,100000):'',captions:typeof v.captions==='string'?v.captions.slice(0,100000):'',rightsConfirmed:v.rightsConfirmed===true};}
async function connection(env){const c=await row(env.DB,'media_connections','youtube');return c;}
async function seal(env,text){if(!/^[0-9a-f]{64}$/.test(env.MEDIA_TOKEN_KEY||''))throw Error('YouTube credential encryption is not configured.');const key=await crypto.subtle.importKey('raw',Uint8Array.from(env.MEDIA_TOKEN_KEY.match(/../g),x=>parseInt(x,16)),{name:'AES-GCM'},false,['encrypt','decrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(text));return {iv:Array.from(iv),data:Array.from(new Uint8Array(data))};}
async function unseal(env,v){const key=await crypto.subtle.importKey('raw',Uint8Array.from(env.MEDIA_TOKEN_KEY.match(/../g),x=>parseInt(x,16)),{name:'AES-GCM'},false,['decrypt']);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(v.iv)},key,new Uint8Array(v.data)));}
async function provider(response){let value;try{value=await response.json();}catch{value={};}if(!response.ok)throw Error(`YouTube returned HTTP ${response.status}${value.error?.errors?.[0]?.reason?' ('+value.error.errors[0].reason+')':''}`);return value;}
async function access(env,fetcher){const c=await connection(env);if(!c?.credential)throw Error('Connect your YouTube channel first.');if(!env.YOUTUBE_CLIENT_ID||!env.YOUTUBE_CLIENT_SECRET)throw Error('YouTube OAuth is not configured.');const refresh=await unseal(env,c.credential);const r=await fetcher('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.YOUTUBE_CLIENT_ID,client_secret:env.YOUTUBE_CLIENT_SECRET,refresh_token:refresh,grant_type:'refresh_token'}),signal:AbortSignal.timeout(20000)});const data=await provider(r);if(typeof data.access_token!=='string')throw Error('YouTube did not return an access token.');return data.access_token;}
async function channels(env,fetcher,token){const data=await provider(await fetcher('https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&mine=true',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)}));const channel=data.items?.[0];if(!channel?.id)throw Error('No YouTube channel was returned.');const c=await connection(env)||{};if(c.channel?.id&&c.channel.id!==channel.id)throw Error('The connected channel changed. Reconnect before executing queued jobs.');c.channel={id:channel.id,title:channel.snippet?.title||channel.id,statistics:channel.statistics||{},observedAt:stamp()};await env.DB.prepare('INSERT INTO media_connections VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET document=excluded.document,updated_at=excluded.updated_at').bind('youtube',JSON.stringify(c),stamp()).run();return c.channel;}
async function governed(govern,id,kind,data){const receipt=await govern({commandId:`media:${id}:${kind}`,capabilityId:'skill://engineering/translation-ledger',namespaceId:'media-owner',input:{kind:'MEDIA_'+kind.toUpperCase(),data}});if(receipt?.state!=='AGENT_EXECUTED')throw Error('BRAINK did not authorize and record this execution.');return {commandId:receipt.commandId,state:receipt.state};}
async function saveJob(env,j){j.updatedAt=stamp();await env.DB.prepare('UPDATE media_jobs SET status=?,lease=?,updated_at=?,document=? WHERE id=?').bind(j.status,j.lease||null,j.updatedAt,JSON.stringify(j),j.id).run();}

async function recoverExpired(env){
 const cutoff=new Date(Date.now()-24*60*60*1000).toISOString();
 const stale=(await env.DB.prepare('SELECT id,document FROM media_jobs WHERE lease IS NOT NULL AND updated_at<?').bind(cutoff).all()).results;
 for(const r of stale){const j=JSON.parse(r.document);const changed=await env.DB.prepare("UPDATE media_jobs SET lease=NULL,status='needs-reconciliation' WHERE id=? AND lease IS NOT NULL AND updated_at<?").bind(r.id,cutoff).run();if(changed.meta.changes){j.lease=null;j.status='needs-reconciliation';j.error='Worker lease expired. Inspect external effects and saved outputs before any retry.';await saveJob(env,j);}}
}
export async function mediaTick(env,govern,fetcher=fetch){
 await recoverExpired(env);
 const candidate=await env.DB.prepare("SELECT id FROM media_jobs WHERE kind!='process-media' AND status IN ('queued','uploading') AND due_at<=? AND lease IS NULL ORDER BY due_at LIMIT 1").bind(stamp()).first();if(!candidate)return {state:'idle'};
 const lease=crypto.randomUUID();const claimed=await env.DB.prepare('UPDATE media_jobs SET lease=?,updated_at=? WHERE id=? AND lease IS NULL').bind(lease,stamp(),candidate.id).run();if(claimed.meta.changes!==1)return {state:'busy'};
 const j=await row(env.DB,'media_jobs',candidate.id);j.lease=lease;
 try{
  if(!j.governance)j.governance=await governed(govern,j.id,'requested',{kind:j.kind,asset:j.assetId,channel:j.channelId});
  const token=await access(env,fetcher);const observed=await channels(env,fetcher,token);if(j.channelId&&j.channelId!==observed.id)throw Error('Queued channel does not match the connected account.');
  if(j.kind==='audience-review'){const data=await provider(await fetcher('https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&allThreadsRelatedToChannelId='+encodeURIComponent(observed.id)+'&maxResults=20&order=time',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)}));j.result={observedAt:stamp(),comments:(data.items||[]).map(item=>({id:item.id,videoId:item.snippet.videoId,text:item.snippet.topLevelComment.snippet.textOriginal,replyDraft:'Thank you for sharing your perspective. What would you like us to explore in a future episode?',draftBoundary:'Draft only; no reply was posted.'}))};j.status='completed';}
  else if(j.kind==='channel-sync'){j.result={channel:observed};j.status='completed';}
  else if(j.kind==='upload-video'){
   const asset=await row(env.DB,'media_assets',j.assetId);if(!asset||asset.kind!=='video')throw Error('YouTube uploads require a video export. Audio podcasts need a video container.');
   if(!j.uploadURL){const status={privacyStatus:j.privacy,selfDeclaredMadeForKids:j.madeForKids};if(j.publishAt)status.publishAt=j.publishAt;
    const r=await fetcher('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-Upload-Content-Type':asset.mime,'X-Upload-Content-Length':String(asset.bytes)},body:JSON.stringify({snippet:{title:j.title,description:j.description,categoryId:'28'},status}),signal:AbortSignal.timeout(20000)});
    if(!r.ok)await provider(r);const location=r.headers.get('location');if(!location||new URL(location).origin!=='https://www.googleapis.com')throw Error('YouTube did not return a trusted upload session.');j.uploadURL=location;j.offset=0;j.status='uploading';await saveJob(env,j);
   }
   const end=Math.min(j.offset+chunkSize,asset.bytes)-1;const object=await env.BUCKET.get(asset.objectKey,{range:{offset:j.offset,length:end-j.offset+1}});if(!object)throw Error('Upload source is missing.');
   const bytes=await object.arrayBuffer();const response=await fetcher(j.uploadURL,{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':asset.mime,'Content-Length':String(bytes.byteLength),'Content-Range':`bytes ${j.offset}-${end}/${asset.bytes}`},body:bytes,signal:AbortSignal.timeout(60000)});
   if(response.status===308){const match=/bytes=0-(\d+)/.exec(response.headers.get('range')||'');if(!match)throw Error('YouTube upload progress is unobserved; reconcile before retrying.');const next=Number(match[1])+1;if(next<=j.offset||next>end+1)throw Error('YouTube upload progress is inconsistent.');j.offset=next;j.status='uploading';}
   else {const result=await provider(response);if(!result.id)throw Error('YouTube did not return a video ID.');j.videoId=result.id;const readback=await provider(await fetcher('https://www.googleapis.com/youtube/v3/videos?part=snippet,status&id='+encodeURIComponent(result.id),{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)}));if(readback.items?.[0]?.id!==result.id)throw Error('YouTube video readback failed.');j.result={videoId:result.id,url:'https://www.youtube.com/watch?v='+result.id,observedStatus:readback.items[0].status,observedAt:stamp()};j.status='completed';}
  }else if(j.kind==='update-metadata'){
   const data=await provider(await fetcher('https://www.googleapis.com/youtube/v3/videos?part=snippet,status&id='+encodeURIComponent(j.videoId),{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)}));const old=data.items?.[0];if(!old||old.snippet.channelId!==observed.id)throw Error('Video is not owned by the connected channel.');j.result=await provider(await fetcher('https://www.googleapis.com/youtube/v3/videos?part=snippet',{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({id:j.videoId,snippet:{...old.snippet,title:j.title,description:j.description}}),signal:AbortSignal.timeout(20000)}));j.status='completed';
  }else throw Error('Unsupported BRAINK media operation.');
  if(j.status==='completed')j.governanceResult=await governed(govern,j.id,'observed',{kind:j.kind,result:j.result});
  j.lease=null;await saveJob(env,j);return {id:j.id,status:j.status};
 }catch(error){j.status=j.uploadURL?'needs-reconciliation':'blocked';j.error=error.message;j.lease=null;await saveJob(env,j);return {id:j.id,status:j.status,error:j.error};}
}

export async function mediaVerify(env,govern){
 const id=crypto.randomUUID(),key='media/verification/'+id,body=JSON.stringify({id,scope:'temporary-object-readback'});
 try{
  const rows=await env.DB.prepare('SELECT COUNT(*) AS count FROM media_assets').first();
  await env.BUCKET.put(key,body);const object=await env.BUCKET.get(key);
  if(!object||await object.text()!==body)throw Error('Media object readback failed');
  const receipt=await governed(govern,id,'transport_observed',{databaseReadback:true,objectReadback:true});
  return json({engine:'BRAINK',databaseReadback:true,objectReadback:true,governance:receipt,assetCount:rows.count,observedAt:stamp(),boundary:'Live media storage and existing BRAINK dispatcher verified. No YouTube account action performed.'});
 }catch(error){return json({error:error.message},503);}finally{await env.BUCKET.delete(key);}
}

export async function mediaService(request,env,govern,fetcher=fetch){
 const u=new URL(request.url),route=u.searchParams.get('route')||'/',actor=request.headers.get('X-Media-Actor')||'owner-agent';
 if(!env.DB||!env.BUCKET)return json({error:'BRAINK media storage is unavailable.'},503);
 try{
  if(route==='/scripts'&&request.method==='GET'){const rows=(await env.DB.prepare('SELECT document FROM media_scripts ORDER BY created_at DESC LIMIT 100').all()).results;return json({scripts:rows.map(x=>JSON.parse(x.document))});}
  if(route==='/scripts'&&request.method==='POST'){const v=await input(request);if(typeof v.title!=='string'||!v.title.trim())return json({error:'Give the script a title.'},400);const doc={id:crypto.randomUUID(),assetId:v.assetId||null,title:v.title.slice(0,100),narration:String(v.narration||'').slice(0,40000),onScreen:String(v.onScreen||'').slice(0,10000),notes:String(v.notes||'').slice(0,10000),audiencePrompt:String(v.audiencePrompt||'').slice(0,1000),createdAt:stamp()};await env.DB.prepare('INSERT INTO media_scripts VALUES(?,?,?,?)').bind(doc.id,doc.assetId,doc.createdAt,JSON.stringify(doc)).run();return json(doc,201);}
  if(route==='/processing/queue'&&request.method==='POST'){
   const v=await input(request),asset=validId(v.assetId)?await row(env.DB,'media_assets',v.assetId):null;
   if((!asset&&!(v.profiles?.length===1&&v.profiles[0]==='voiceover'&&v.voiceScript))||v.rightsConfirmed!==true||!Array.isArray(v.profiles)||!v.profiles.length||v.profiles.some(x=>!['shorts','long','podcast','voiceover','animate'].includes(x)))return json({error:'Select an existing source, processing formats and confirm rights.'},400);
   if(asset?.kind==='audio'&&v.profiles.some(x=>!['podcast','voiceover'].includes(x)))return json({error:'Audio sources currently support podcast mastering; use a video source for shorts or long video.'},400);
   if(asset?.kind==='image'&&(v.profiles.length!==1||v.profiles[0]!=='animate'))return json({error:'Image sources support the animation profile only.'},400);
   if(v.profiles.includes('animate')&&asset?.kind!=='image')return json({error:'Animation requires a saved PNG, JPEG or WebP image.'},400);
   const id=crypto.randomUUID(),j={id,kind:'process-media',status:'queued',assetId:asset?.id||null,profiles:v.profiles,options:{profiles:v.profiles,title:String(v.title||asset?.name||"Voice-over").slice(0,100),description:String(v.description||'').slice(0,5000),shortSeconds:Number(v.shortSeconds)||30,maxShorts:Math.min(10,Math.max(1,Number(v.maxShorts)||3)),transcribe:v.transcribe===true,voiceScript:String(v.voiceScript||'').slice(0,20000),animationSeconds:Number(v.animationSeconds)||10},autoQueueYouTube:v.autoQueueYouTube===true,rightsConfirmed:true,createdAt:stamp(),updatedAt:stamp(),dueAt:stamp()};
   await env.DB.prepare('INSERT INTO media_jobs VALUES(?,?,?,?,?,?,?,?)').bind(id,j.kind,j.status,j.dueAt,null,j.createdAt,j.updatedAt,JSON.stringify(j)).run();return json(j,201);
  }
  if(route==='/processing/claim'&&request.method==='POST'){
   await recoverExpired(env);
   const candidate=await env.DB.prepare("SELECT id FROM media_jobs WHERE kind='process-media' AND status='queued' AND lease IS NULL ORDER BY created_at LIMIT 1").first();if(!candidate)return json({state:'idle'});
   const lease=crypto.randomUUID();const updated=await env.DB.prepare("UPDATE media_jobs SET lease=?,status='processing',updated_at=? WHERE id=? AND lease IS NULL AND status='queued'").bind(lease,stamp(),candidate.id).run();if(updated.meta.changes!==1)return json({state:'busy'});
   const j=await row(env.DB,'media_jobs',candidate.id);j.lease=lease;j.status='processing';try{j.governance=await governed(govern,j.id,'processing_requested',{assetId:j.assetId,profiles:j.profiles});await saveJob(env,j);}catch(error){j.status='blocked';j.error=error.message;j.lease=null;await saveJob(env,j);return json({error:j.error,id:j.id,status:j.status},503);}const asset=j.assetId?await row(env.DB,'media_assets',j.assetId):null;return json({job:j,asset});
  }
  if(route==='/processing/finish'&&request.method==='POST'){
   const v=await input(request),j=await row(env.DB,'media_jobs',v.id);if(!j||j.kind!=='process-media'||!j.lease||j.lease!==v.lease)return json({error:'Processing lease does not match.'},409);
   if(v.error){j.status='blocked';j.error=String(v.error).slice(0,2000);}else{
    if(!Array.isArray(v.outputs)||!v.outputs.length)return json({error:'Processing output observations are missing.'},400);
    for(const output of v.outputs){const asset=await row(env.DB,'media_assets',output.assetId);if(!asset)throw Error('A generated output has not been stored in the library.');}
    j.result={outputs:v.outputs,processingEvidence:v.evidence};j.status='completed';j.governanceResult=await governed(govern,j.id,'processing_observed',{outputs:v.outputs.map(x=>({assetId:x.assetId,name:x.name,bytes:x.bytes})),tools:v.evidence?.tools});
    if(j.autoQueueYouTube){const c=await connection(env);if(!c?.channel?.id){j.result.youtube='Not queued: connect a channel first.';}else for(const output of v.outputs.filter(x=>x.kind==='video')){const id=crypto.randomUUID(),next={id,kind:'upload-video',status:'queued',assetId:output.assetId,channelId:c.channel.id,title:String(output.title||output.name).slice(0,100),description:String(output.description||'').slice(0,5000),privacy:'private',publishAt:null,madeForKids:false,createdAt:stamp(),updatedAt:stamp(),dueAt:stamp()};await env.DB.prepare('INSERT INTO media_jobs VALUES(?,?,?,?,?,?,?,?)').bind(id,next.kind,next.status,next.dueAt,null,next.createdAt,next.updatedAt,JSON.stringify(next)).run();}}
   }
   j.lease=null;await saveJob(env,j);return json({id:j.id,status:j.status,result:j.result,error:j.error});
  }
  if(route==='/status'&&request.method==='GET'){const c=await connection(env);return json({engine:'BRAINK',channel:c?.channel||null,connected:!!c?.credential,oauthConfigured:!!(env.YOUTUBE_CLIENT_ID&&env.YOUTUBE_CLIENT_SECRET&&env.MEDIA_TOKEN_KEY),agentConfigured:!!env.BRAINK_MEDIA_AGENT_TOKEN,boundary:'Execution records and YouTube provider observations are separate. No account activity is fabricated.'});}
  if(route==='/library'&&request.method==='GET'){const assets=(await env.DB.prepare('SELECT document FROM media_assets ORDER BY created_at DESC LIMIT 200').all()).results;const edits=(await env.DB.prepare('SELECT document FROM media_edits ORDER BY created_at DESC LIMIT 500').all()).results;const jobs=(await env.DB.prepare('SELECT document FROM media_jobs ORDER BY created_at DESC LIMIT 100').all()).results;return json({assets:assets.map(x=>JSON.parse(x.document)),edits:edits.map(x=>JSON.parse(x.document)),jobs:jobs.map(x=>{const j=JSON.parse(x.document);delete j.uploadURL;delete j.lease;return j;})});}
  if(route==='/upload/start'&&request.method==='POST'){const v=await input(request);if(!['video','audio','image'].includes(v.kind)||typeof v.mime!=='string'||(!v.mime.startsWith(v.kind+'/')||(v.kind==='image'&&!['image/png','image/jpeg','image/webp'].includes(v.mime)))||!Number.isSafeInteger(v.bytes)||v.bytes<=0||v.bytes>maxBytes||typeof v.name!=='string'||v.name.length>240)return json({error:'Use a video or audio file up to 2 GB with a recognised media type.'},400);const id=crypto.randomUUID(),key='media/originals/'+id;const multipart=await env.BUCKET.createMultipartUpload(key,{httpMetadata:{contentType:v.mime}});const document={id,actor,name:v.name,kind:v.kind,mime:v.mime,bytes:v.bytes,objectKey:key,uploadId:multipart.uploadId,parts:[],createdAt:stamp()};await env.DB.prepare('INSERT INTO media_uploads VALUES(?,?,?,?)').bind(id,actor,JSON.stringify(document),stamp()).run();return json({id,chunkSize},201);}
  if(route==='/upload/part'&&request.method==='PUT'){const id=u.searchParams.get('id'),number=Number(u.searchParams.get('part'));if(!validId(id)||!Number.isInteger(number)||number<1)return json({error:'Invalid upload part.'},400);const v=await row(env.DB,'media_uploads',id);if(!v||v.actor!==actor)return json({error:'Upload not found.'},404);const length=Number(request.headers.get('Content-Length'));if(!Number.isSafeInteger(length)||length<1||length>chunkSize)return json({error:'Chunk length must be between 1 byte and 8 MiB.'},413);const bytes=await request.arrayBuffer();const expected=Math.min(chunkSize,v.bytes-(number-1)*chunkSize);if(bytes.byteLength!==expected)return json({error:'Chunk does not match the declared file size.'},400);const sha256=await hash(bytes);const prior=v.parts.find(p=>p.partNumber===number);if(prior){if(prior.sha256!==sha256)return json({error:'This part number was already uploaded with different bytes.'},409);return json(prior);}
   const part=await env.BUCKET.resumeMultipartUpload(v.objectKey,v.uploadId).uploadPart(number,bytes);v.parts.push({...part,sha256,bytes:bytes.byteLength});await env.DB.prepare('UPDATE media_uploads SET document=?,updated_at=? WHERE id=?').bind(JSON.stringify(v),stamp(),id).run();return json(v.parts.at(-1));}
  if(route==='/upload/complete'&&request.method==='POST'){const v=await input(request);if(!validId(v.id))return json({error:'Invalid upload.'},400);const prior=await row(env.DB,'media_assets',v.id);if(prior)return json(prior);const upload=await row(env.DB,'media_uploads',v.id);if(!upload||upload.actor!==actor)return json({error:'Upload not found.'},404);const parts=upload.parts.sort((a,b)=>a.partNumber-b.partNumber);if(parts.length!==Math.ceil(upload.bytes/chunkSize)||parts.some((p,i)=>p.partNumber!==i+1)||parts.reduce((n,p)=>n+p.bytes,0)!==upload.bytes)return json({error:'Upload is incomplete. Retry the missing chunks.'},409);let object=await env.BUCKET.head(upload.objectKey);if(!object){await env.BUCKET.resumeMultipartUpload(upload.objectKey,upload.uploadId).complete(parts.map(({partNumber,etag})=>({partNumber,etag})));object=await env.BUCKET.head(upload.objectKey);}if(!object||object.size!==upload.bytes)throw Error('Stored media size readback failed.');const document={id:upload.id,name:upload.name,kind:upload.kind,mime:upload.mime,bytes:upload.bytes,createdAt:upload.createdAt,objectKey:upload.objectKey,integrity:{kind:'ordered-chunk-sha256-manifest',parts:parts.map(({sha256,bytes})=>({sha256,bytes}))}};const manifestHash=await hash(new TextEncoder().encode(JSON.stringify(document.integrity)));await env.DB.prepare('INSERT OR IGNORE INTO media_assets VALUES(?,?,?,?,?,?,?,?,?,?)').bind(document.id,actor,document.name,document.kind,document.mime,document.bytes,document.objectKey,manifestHash,document.createdAt,JSON.stringify(document)).run();return json(document,201);}
  if(route==='/asset'&&['GET','HEAD'].includes(request.method)){const id=u.searchParams.get('id');if(!validId(id))return json({error:'Invalid asset.'},400);const asset=await row(env.DB,'media_assets',id);if(!asset)return json({error:'Media not found.'},404);const match=/^bytes=(\d+)-(\d*)$/.exec(request.headers.get('Range')||'');let range;if(match){const start=Number(match[1]),end=match[2]?Number(match[2]):asset.bytes-1;if(start>=asset.bytes||end<start)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${asset.bytes}`}});range={offset:start,length:Math.min(end,asset.bytes-1)-start+1};}const object=await env.BUCKET.get(asset.objectKey,range?{range}:undefined);if(!object)return json({error:'Stored media is unavailable.'},503);const h={'Content-Type':asset.mime,'Accept-Ranges':'bytes','Content-Length':String(range?range.length:asset.bytes),'Cache-Control':'private,no-store'};if(range)h['Content-Range']=`bytes ${range.offset}-${range.offset+range.length-1}/${asset.bytes}`;return new Response(request.method==='HEAD'?null:object.body,{status:range?206:200,headers:h});}
  if(route==='/edits'&&request.method==='POST'){const v=await input(request);if(!validId(v.assetId)||!await row(env.DB,'media_assets',v.assetId))return json({error:'Choose an existing media file.'},400);const edit={id:crypto.randomUUID(),assetId:v.assetId,...validateEdit(v),createdAt:stamp()};await env.DB.prepare('INSERT INTO media_edits VALUES(?,?,?,?)').bind(edit.id,edit.assetId,edit.createdAt,JSON.stringify(edit)).run();return json(edit,201);}
  if(route==='/oauth/start'&&request.method==='POST'){if(!env.YOUTUBE_CLIENT_ID||!env.YOUTUBE_CLIENT_SECRET||!env.MEDIA_TOKEN_KEY)return json({error:'YouTube connection needs the Google OAuth client configured in BRAINK. No account is connected.'},503);const state=crypto.randomUUID();await env.DB.prepare('INSERT INTO media_oauth_states VALUES(?,?,?)').bind(state,actor,new Date(Date.now()+600000).toISOString()).run();const target=new URL('https://accounts.google.com/o/oauth2/v2/auth');target.search=new URLSearchParams({client_id:env.YOUTUBE_CLIENT_ID,redirect_uri:'https://www.keddeh.com/api/media/oauth/callback',response_type:'code',scope:'https://www.googleapis.com/auth/youtube.force-ssl https://www.googleapis.com/auth/youtube.upload',access_type:'offline',prompt:'consent',state}).toString();return json({url:target.href});}
  if(route==='/oauth/callback'&&request.method==='GET'){const state=u.searchParams.get('state'),code=u.searchParams.get('code');if(!validId(state)||!code)return json({error:'YouTube consent was not completed.'},400);const consumed=await env.DB.prepare('DELETE FROM media_oauth_states WHERE id=? AND actor=? AND expires_at>? RETURNING id').bind(state,actor,stamp()).first();if(!consumed)return json({error:'The connection request expired or belongs to another session.'},400);const response=await fetcher('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.YOUTUBE_CLIENT_ID,client_secret:env.YOUTUBE_CLIENT_SECRET,code,grant_type:'authorization_code',redirect_uri:'https://www.keddeh.com/api/media/oauth/callback'}),signal:AbortSignal.timeout(20000)});const data=await provider(response);if(!data.refresh_token)throw Error('Google did not return an offline credential. Reconnect with consent.');await env.DB.prepare('INSERT INTO media_connections VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET document=excluded.document,updated_at=excluded.updated_at').bind('youtube',JSON.stringify({credential:await seal(env,data.refresh_token)}),stamp()).run();await channels(env,fetcher,data.access_token);return Response.redirect('https://www.keddeh.com/sector?connected=1',303);}
  if(route==='/jobs'&&request.method==='POST'){const v=await input(request);if(!['upload-video','channel-sync','update-metadata','audience-review'].includes(v.kind))return json({error:'Unsupported YouTube action.'},400);const c=await connection(env);if(!c?.channel?.id)return json({error:'Connect and verify a YouTube channel before queueing account actions.'},409);let edit={};if(!['channel-sync','audience-review'].includes(v.kind)){edit=validateEdit(v);if(!edit.rightsConfirmed)return json({error:'Confirm you own or may publish this media.'},400);}if(v.kind==='upload-video'){const asset=await row(env.DB,'media_assets',v.assetId);if(!asset||asset.kind!=='video')return json({error:'Select a saved video export. Audio must be exported as video first.'},400);}if(v.kind==='update-metadata'&&!/^[A-Za-z0-9_-]{11}$/.test(v.videoId||''))return json({error:'Enter a valid YouTube video ID.'},400);if(v.publishAt&&(!Number.isFinite(Date.parse(v.publishAt))||Date.parse(v.publishAt)<Date.now()+120000))return json({error:'Scheduled publication must be at least two minutes in the future.'},400);const privacy=v.publishAt?'private':v.privacy||'private';if(!['private','unlisted','public'].includes(privacy))return json({error:'Choose a valid visibility.'},400);const id=crypto.randomUUID(),j={id,kind:v.kind,status:'queued',assetId:v.assetId||null,videoId:v.videoId||null,channelId:c.channel.id,...edit,privacy,publishAt:v.publishAt||null,madeForKids:v.madeForKids===true,createdAt:stamp(),updatedAt:stamp(),dueAt:stamp()};await env.DB.prepare('INSERT INTO media_jobs VALUES(?,?,?,?,?,?,?,?)').bind(id,j.kind,j.status,j.dueAt,null,j.createdAt,j.updatedAt,JSON.stringify(j)).run();return json(j,201);}
  if(route==='/agent/run'&&request.method==='POST')return json(await mediaTick(env,govern,fetcher));
  if(route==='/jobs/cancel'&&request.method==='POST'){const v=await input(request);const changed=await env.DB.prepare("UPDATE media_jobs SET status='cancelled',updated_at=? WHERE id=? AND status='queued' AND lease IS NULL").bind(stamp(),v.id).run();if(!changed.meta.changes)return json({error:'Only an unclaimed queued job can be cancelled.'},409);const j=await row(env.DB,'media_jobs',v.id);j.status='cancelled';await saveJob(env,j);return json({id:j.id,status:j.status});}
  return json({error:'Media operation not found.'},404);
 }catch(error){console.error('BRAINK_MEDIA_OPERATION',error?.name);return json({error:error.message||'BRAINK media operation failed.'},503);}
}
