#!/usr/bin/env python3
"""Generate cross-linked operational contracts and a source API inventory."""
import ast
import json
from pathlib import Path
repo=Path(__file__).resolve().parents[1];docs=repo/'docs/package'
actions={
'prepare':('Admit exact owner sources','Create a fresh private root from the library manifest and configured port offset. Existing nonempty roots are rejected.','python -m keddeh_namespace.web4_runtime prepare --root /private/new-family --library /private/library/manifest.json','Use once when commissioning a new family; compare admitted source hashes before activation.','An operator provisions a repository family without overwriting an existing journal.'),
'start':('Activate an admitted family','Launch original broker, agent, MCP, HTTP actuator and workstations, read ten identities and wait for the current BOOT_SUBSTRATE completion.','bash .keddeh/launch-family.sh','Use the repository launcher for repeatable startup and binding; it preserves mutable state and resumes admitted domains.','Restart an evaluation environment while retaining signed namespace history.'),
'serve':('Run the owner supervisor','The detached controller owns process groups, authenticated gateway, bilateral governor, domain resumption and VFS polling. This foreground entry is normally invoked by start.','python -m keddeh_namespace.web4_runtime serve --root /private/family','Use under an approved Linux process manager; only one controller may hold the root lock.','A cloud instance runs a persistent family from its own configuration and keys.'),
'status':('Read actual runtime health','Read workstation health/telemetry, current boot state and owned service PID status; a bound port alone is insufficient.','cloud status','Read after every start/recovery. Ten healthy workstations and current completed boot establish the local package readiness scope.','An operator distinguishes a live family from an open socket or bundled historical receipt.'),
'boot':('Execute broker/agent substrate boot','Queue the supplied six-phase BOOT_SUBSTRATE command; preserve any queued/leased command rather than overwriting it. The paired outbound agent returns bound readbacks.','cloud boot','Use when the owner requests boot lifecycle execution; read current boot completion before a second command.','The owner re-evaluates mount, targets, writable state and capabilities through the supplied runtime.'),
'restart':('Recover an owned service','Restart only a service declared in the supervisor specification. Process-group cleanup includes child workers; stdio MCP is reinitialized. Restart requests return PIDs and require health readback.','cloud restart node-19100','Select an existing owned service name. Automatic recovery applies to all managed roles with bounded retry rate.','Recover an exited workstation, broker, agent or actuator without adopting a foreign process.'),
'stop':('Stop the host controller cleanly','Stop owned host subprocess groups and wait for the controller root lock to release. Docker domain families retain their separately supervised persistent state and restart policy.','python -m keddeh_namespace.web4_runtime stop --root /private/family','Preserve journals and keys; this is a lifecycle operation, not state deletion. Stop domain containers separately only through an explicit owned-domain maintenance procedure.','Perform a controller upgrade while the retained domain state remains available for rehydration.'),
'commit':('Actuate a durable R36 register','Validate integer node_id 1–11, nonce 0–4294967295 and a nonempty tenant_id of at most 128 characters. The original actor commits durable journal bytes; the namespace signs its returned evidence.','cloud commit 1 42 TENANT','Reuse the same tenant/node/nonce to retry idempotently. Registers are software execution targets; do not interpret them as hardware energy readings.','A runtime transaction applies one explicit register value and retains its actor receipt.'),
'propagate':('Compute and optionally actuate propagation','Accept directed adjacency, optional initial values, steps 1–1000 and boolean actuate. Compute the common software model; optional output mapping clamps to [0,1] and rounds to uint32 across declared R36 registers.','cloud propagate | cloud enact','Read model state and actor receipts. Multi-register execution retains a valid prefix and is not a single atomic hardware transaction.','Explore a directed topology, then explicitly project its software result into admitted register actuation.'),
'bilateral':('Run persistent bilateral execution','With no enabled field, read retained cycle/pending/phase state. enabled=true resumes; false pauses while retaining unfinished intent. Every cycle consumes actual workstation/domain feedback and prior R36 returns.','cloud bilateral start | pause | status','Use continuous execution when an owner family should power its own software control path. Confirm status=operating and returned actors; retrying/paused preserve diagnostic state.','Resume an interrupted cycle after a controller restart without discarding a committed register prefix.'),
'domains':('Operate recursive dual-network domains','operation=status reads namespace and bridge telemetry. spawn creates one own downstream domain and upstream anchor; parent is required after genesis. reanchor takes domain and parent and rejects cyclic lineage.','cloud domains','Maintain an acyclic admitted tree. The configured local capacity is eight domains per family; bridges are internal and containers use pinned carrier bytes and owner workstation sources.','A descendant retains its own network and epoch while its intermediate parent disappears and it reanchors.'),
'vfs':('Read VFS synchronization and subscription','Read durable subscription cursor, cached package path/digest map, published family digest and actor/observer receipt status. Configured polling retries without executing downloaded packages.','cloud vfs','Inspect status=subscribed and exact bundle digest. A cache update is not automatic promotion or independent public production assessment.','A deployment receives a new qualified package artifact while continuing its active bilateral runtime.'),
'hci':('Render Shared KEDDEH operator console','Bind the supplied HCI header/footer/evidence-trace pattern to actual runtime, bilateral and domain readbacks. Mock watchdog/quorum/slot strings are excluded from operational claims.','cloud hci','Use the console to see state and explicit owner controls. Independent ISO certification is not implied by the rendering method names.','An operator reviews the execution context and chooses a visible, purposeful next action.'),
'observer':('Build an owner periodic definition node','Call the supplied definition_node_compiler.make_node with identity, cloud context, observer descriptor and registry evidence path.','cloud observer','Use the returned definition for owner observation workflows; its local evidence path is not an external assessor report.','Represent the active runtime as an owner observer node with explicit context and evidence.'),
'workbook':('Run current owner workbook diagnostics','Invoke the supplied workbook_adapter.diagnostic_run and return fresh findings. Bundled historical receipts are not counted as current qualification.','cloud workbook','Review findings before expanding capabilities. Existing broader-estate missing-module findings remain visible rather than being suppressed.','Determine which parts of a supplied estate currently resolve in the admitted family.'),
'estate':('Call admitted owner MCP estate tools','Invoke only exposed tools: estate_status, mesh_discover, mesh_status, mesh_aggregate, mesh_verify_evidence, host_agent_capabilities, lexicon_stats, bilateral_summary and dependency_frontier.','POST /api/web4/control {action: estate, tool: mesh_status, arguments: {}}','Use existing owner tool identities; mesh_read_status aliases mesh_status. Arbitrary shell and nonadmitted side-effect tools are not exposed.','Read live mesh aggregation or bilateral capability relationships through the supplied MCP implementation.')}
processes={
'controller':('Host lifecycle and owner dispatch','keddeh_namespace.web4_runtime serve','Private launch/state root and token-authenticated gateway','Source-bound receipts, owned process health and current boot readback','Cloud family supervisor; all control requests route through KCloudNode.'),
'broker':('Owner command/lease rendezvous','owner_broker.py','Private broker state, paired agent identity, sequence and pending command','Bound terminal lease result and hash-chained ledger','BOOT_SUBSTRATE and owner lifecycle execution; partial commands retain leases.'),
'agent':('Persistent outbound owner actuator','kex-host-agent.py','Broker URL, private state file, owner workspace and one-second poll','Six boot-phase results with actual fsync/write/readback evidence','Run owner commands without requiring an inbound foreign operator shell.'),
'network':('Original network MCP executable','braink-chatgpt-plugin/server/dist/src/server.js','Separate network journal, route ledger and verification ledger','MCP initialization and actual commit receipt','Network executable evaluation separate from HTTP4055 journal ownership.'),
'http':('Original R36 HTTP actuator harness','dist-http4055/server/http4055Harness.js','Private configured loopback port and HTTP journal path','ACTOR_COMMITTED with durable 48-byte journal record','Mapped software register actuation and idempotent recovery.'),
'http-worker':('Original Python core execution worker','braink_core_runtime.py','Harness stdio and per-family journal file','Deterministic register receipt recovered from durable bytes','Worker child shares its owned process group and is cleaned up on harness restart.'),
'estate':('Owner estate stdio MCP','server/braink_mcp.py --stdio','Admitted v5.7 estate plus exact overlays and isolated mutable estate data','Initialize and allowed tool results','Current capability discovery, mesh status and owner bilateral registry.'),
'bilateral-governor':('Persistent execution/feedback schedule','keddeh_namespace.bilateral_runtime','Actual workstation/domain telemetry, owner PLL and healing, pending register intent','Ten actual actor returns and signed cycle generation','Runs inside controller every five seconds; no fabricated stochastic measurement.'),
'vfs-subscriber':('Durable package subscription and family mirror','keddeh_namespace.vfs_subscription','Declared local VFS endpoint and private token-file reference','Verified downloaded bundle hash, cursor acknowledgement and mirrored predecessor chain','Runs inside controller; caches updates and preserves local execution during hub loss.'),
'vfs-server':('Owner artifact graph and observer receipts','vfs_server.server','Private VFS root, WAL/FULL SQLite, mutation token file','/ready plus separate artifact readback and observer receipt','Supervised by the primary VFS family; both VFS repositories retain its source/package.'),
'domain-bridge':('Dual-homed recursive transport','web4_domain.mjs','Own downstream network, upstream parent URL, private token and persisted epoch/phase','Distinct /proc network namespace, parent bridge telemetry and flywheel continuity','Independent container runtime; unchanged downstream network across reanchoring.'),
'domain-workstations':('Three owner process heaps per network domain','Exact kex_server_space_workstation.js source','Namespace-local ports 19100–19102 and inherited immutable owner code','Three owner PIDs and telemetry/compute state','A local triad operates within each recursive virtual domain; ports repeat across isolated namespaces.')}
for i in range(10):processes[f'workstation-{i+1:02}']=('Admitted owner workstation execution',f'Owner mesh registry node {i+1}',f'Family mesh port offset plus {19100+i}; exact source identity','Actual health domain, computeCycles and double-SHA-256 stateHash','One mapped node in the ten-service host estate; 25ms software state cycling is not external mining proof.')
configs={
'family-manifest':('repository, family_id, engine_repository, engine_ref','Pins repository attribution and owner engine revision. Do not reuse another family id or bind an existing root to a different repository.'),
'family-storage':('runtime_root, library_manifest','Absolute private writable roots outside Git. Library bytes must match custody SHA-256; prepare never overwrites an existing nonempty root.'),
'family-ports':('port_offset, launch.ports.gateway/network/http/broker/mesh','Use a distinct offset per family. Bind loopback APIs; root startup rejects occupied ports rather than adopting foreign listeners.'),
'vfs-binding':('vfs.endpoint, vfs.token_file','This cloud binding accepts the declared http://127.0.0.1 endpoint. token_file is a private file reference, not a credential value in Git. Subscriber prefix is /packages/web4.'),
'vfs-hub':('vfs_hub.code_root/state_root/port/token_file','Only the primary VFS family supervises the shared hub. Use its actual checked-out owner VFS implementation, persisted artifact graph and private token file.'),
'source-admission':('launch.packages/estate/sources/files/derivations/scope','Owner source custody plus derived file SHA-256. verify_launch rejects mutated/missing/symlinked admitted package files. Runtime-source-manifest binds the active engine files.'),
'private-identity':('state/token, pairing-code, generator.key, trust.json','Generated private bearer credential, owner pairing key and Ed25519 generator key/trust role bindings. Preserve on restart; do not print, commit or embed in customer JavaScript.'),
'bilateral-state':('enabled, cycle, pending, last, phase, status, error','Durable enabled intent, partially returned register prefix and owner software PLL vector. Explicit pause preserves intent; restart does not silently reset a phase or register transaction.'),
'domain-topology':('enabled, domains[].id/parent/upstream/downstream/image/owner_source_sha256/bridge_sha256','Acyclic recursive dual-network tree with exact owner code and pinned carrier. Every child keeps its own downstream bridge when reanchoring; local capacity eight domains.'),
'domain-phase':('domain, epoch, theta, omega, elapsed, children, mode, anchor, workstation, workstations','Persisted owner software oscillator and actual local runtime readbacks. Parent loss enters FLYWHEEL without resetting child epoch. This is not a physical power-meter reading.'),
'vfs-subscription-state':('cursor, objects, published_digest, actor_receipt, observer_receipt, status, error','Cursor advances only after a processed event is durable. Package bytes are hash-verified in a private content-addressed mirror. Subscription progress is acknowledged by VFS_SERVER.'),
'process-envelope':('RLIMIT_CORE/NOFILE/FSIZE, restart backoff, Docker memory/cpus/pids-limit/cap-drop/read-only','Host children disable core dumps and bound descriptors/output. Domain containers additionally use 128MiB memory,0.5 CPU,64 processes,read-only code,no added Linux capabilities and explicit state mounts.'),
'ci-and-build':('uv.lock, build-constraints.txt, workflow action SHAs, qualification output','Frozen runtime dependencies and pinned build tool/action versions. Candidate evidence must be outside source; dirty checkouts fail. No hosted CI pass is claimed while billing prevents jobs from starting.')}
for section,records in [('actions',actions),('processes',processes),('configuration',configs)]:
 for key,value in records.items():
  directory=docs/section/key;directory.mkdir(parents=True,exist_ok=True)
  if section=='actions':
   title,function,command,guide,case=value;body=f'# {title}\n\n## Function and architectural application\n\n{function}\n\n## User guidelines\n\n{guide}\n\n## Entry and expected context\n\n`{command}`\n\n## Fit, case and field use\n\n{case}\n\n## Supporting source and evidence\n\nSee `src/keddeh_namespace/web4_runtime.py`, the owner source manifest, process contracts and full qualification logs. The gateway accepts authenticated owner actions; customer frontage has a separate access boundary.\n'
  elif section=='processes':
   title,source,inputs,result,fit=value;body=f'# {key}: {title}\n\n## Function and architectural application\n\nSource/entry: `{source}`.\n\n## Configuration and inputs\n\n{inputs}.\n\n## Readback and attribution\n\n{result}. Source custody and active runtime fingerprints identify the actual execution.\n\n## Fit, case and field use\n\n{fit}\n\n## Operator guidelines\n\nRead actual health after launch/recovery, retain state and credentials, and use the owning family supervisor. Actor results and independent production assessment are different evidence scopes.\n'
  else:
   fields,guide=value;body=f'# {key}\n\n## Configuration fields\n\n`{fields}`\n\n## Function and architectural application\n\n{guide}\n\n## Guidelines, fit and field use\n\nUse this contract when commissioning, qualifying or recovering an owner family. Match its values to the selected repository and actual host bindings; retain predecessor state and verify readbacks after changes.\n\n## Supporting documents\n\nSee the family manifest, OWNER_ENVIRONMENT.md, package README and corresponding process/action contracts.\n'
  (directory/'README.md').write_text(body)
 index='# '+section.title()+'\n\n'+''.join(f'- [{key}]({key}/README.md)\n' for key in records)
 (docs/section/'README.md').write_text(index)
entries=[]
for p in sorted((repo/'src/keddeh_namespace').glob('*.py')):
 tree=ast.parse(p.read_text());module_doc=ast.get_docstring(tree) or p.stem
 for node in tree.body:
  groups=[(node,'')] if isinstance(node,(ast.FunctionDef,ast.AsyncFunctionDef)) else [(n,node.name+'.') for n in node.body if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef))] if isinstance(node,ast.ClassDef) else []
  for fn,prefix in groups:
   entries.append({'module':p.stem,'function':prefix+fn.name,'signature':ast.unparse(fn.args),'line':fn.lineno,'purpose':ast.get_docstring(fn) or module_doc,'visibility':'internal' if fn.name.startswith('_') and fn.name!='__init__' else 'source-api','calls':sorted({ast.unparse(n.func) for n in ast.walk(fn) if isinstance(n,ast.Call)})})
(repo/'docs/package/SOURCE_API.json').write_text(json.dumps(entries,indent=2)+'\n')
body='# Source API inventory\n\nThis catalog records each source function/method and its actual signature, source line and call relationships. Supported owner journeys are documented separately in action/process contracts; internal methods are implementation interfaces.\n\n'
for row in entries:
 body+=f"## {row['module']}.{row['function']}\n\n`({row['signature']})`\n\n{row['purpose']}\n\nSource: `src/keddeh_namespace/{row['module']}.py:{row['line']}`. Calls: "+', '.join('`'+n+'`' for n in row['calls'])+'.\n\n'
(docs/'SOURCE_API.md').write_text(body)
required=set()
for node in ast.walk(ast.parse((repo/'src/keddeh_namespace/web4_runtime.py').read_text())):
 if isinstance(node,ast.Compare) and isinstance(node.left,ast.Name) and node.left.id=='action':
  for term in node.comparators:
   if isinstance(term,ast.Constant) and isinstance(term.value,str):required.add(term.value)
if required-set(actions):raise SystemExit('Undocumented actions: '+str(required-set(actions)))
report={'schema':'keddeh.package-doc-coverage.v1','actions':len(actions),'processes':len(processes),'configuration_groups':len(configs),'source_functions':len(entries),'gateway_actions':sorted(required),'undocumented_gateway_actions':[]}
(docs/'COVERAGE.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
